### PR TITLE
feat(docs, netlify): Netlify Configuration

### PR DESCRIPTION
**Pull request by im-coder-lg**
Simple for now, but it _might_ get extensive later on.

Will help us configure builds.
Netlify config, urgent merge. Ready.
Created a Netlify tag too, since we'll have two kinds of errors on deployment: 
1. Docusaurus
2. Netlify(most likely since Docusaurus is customised to stop most errors).
Urgent merge+Netlify deploy _needed_.

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Netlify will fail. Unless we configure it.

**Comment by im-coder-lg** [comment]
yo, @sumeshir26 I sent a request to you to join as a reviewer in Netlify. Also @not-nef you too sign up and get a reviewer role. It's free they say.

**Comment by im-coder-lg** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/sumeshir26/reviewers)

**Comment by im-coder-lg** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/sumeshir26/reviewers)

**Comment by im-coder-lg** [comment]
That new user is me btw

**Comment by im-coder-lg** [comment]
Also, I have a frank request. There is a new beta for GitHub Projects that organises everything into tables or boards. With your request, I will start a convenient issue tracker that everyone can see and help on.

**Comment by im-coder-lg** [comment]
Oh, just realized - they are only for a global user account. It's gonna make triaging hard for us, especially me since I like a good tabled view.

**Comment by im-coder-lg** [comment]
But also - multiple projects can be added with collaborators, meaning we could have a _literally convienient_ issue tracker.

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
I will merge this. It's urgent.

**Comment by im-coder-lg** [comment]
Gitpod worked btw

**Pull request merged**
