### PR TITLE
feat: New Icon +Sun Valley theming in configurator.py

### LINKED ISSUE #15: app.wm_attributes(„-transparent“, „green“)
Hey There!

I am trying to run the script on macos 10.13.6 and on line 24 it throws me the following Error:

```
Traceback (most recent call last):
 File "/Users/***/Downloads/TimerX-master/main.py", line 24, in <module>
  app.wmattributes("-transparent", "green")
 File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 2005, in wm_attributes
  return self.tk.call(args)
_tkinter.TclError: expected boolean value but got "green"
```

When i delete that line, the application seems to run fine.

### PR DESCRIPTION
**Pull request by not-nef**
Adds a new icon and adds Sun Valley style to entry
Fixes #15 

banner_new

### CODE REVIEW

**Comment by im-coder-lg** [comment]
That. That is so cool! Can you make an icon with the new curved clock icon and upload here? I'll try adding suggestions so that I could help you in this.

**Comment by not-nef** [comment]
Can you explain what curved clock icon you mean?

**Comment by sumeshir26** [comment]
@not-nef He means the icon you put on the banner.

**Comment by not-nef** [comment]
Ah, oke

**Comment by not-nef** [comment]
Done! @im-coder-lg

**Comment by not-nef** [comment]
image

the uploaded version is transparent

**Comment by im-coder-lg** [comment]
That. Is. Excellent. Let's get this PR ready for merging! @not-nef can you test the new icon on macOS? We'll manage on Windows.

**Comment by not-nef** [comment]
macos doesnt display icons for programs @im-coder-lg

**Comment by im-coder-lg** [comment]
What about the dock? PS: My commit incoming!

**Comment by im-coder-lg** [comment]
Also, @not-nef from now, create a new branch from the `master` branch when coding, so you don't mess up your codebase and you can always revert back.

**Comment by im-coder-lg** [comment]
Title change request to `feat: New Banner+Sun Valley theming in configurator`.

**Comment by sumeshir26** [comment]
@not-nef @im-coder-lg I reallay like the new icon but I am not so sure about the new banner. I will create a new banner with the new icon but with the existing style of the current banner.

**Comment by sumeshir26** [comment]
> Title change request to `feat: New Banner+Sun Valley theming in configurator`.

Done!

**Comment by sumeshir26** [comment]
@not-nef The icon's background is too dark, can you make it lighter? It dosent look good on the Taskbar.

**Comment by sumeshir26** [comment]
And even, could you show me **your** banner with the background as white?

**Comment by not-nef** [comment]
> @not-nef The icon's background is too dark, can you make it lighter? It dosent look good on the Taskbar.

Can do later this day

**Comment by not-nef** [comment]
> @not-nef @im-coder-lg I reallay like the new icon but I am not so sure about the new banner. I will create a new banner with the new icon but with the existing style of the current banner.

i like the banner but ok

**Comment by im-coder-lg** [comment]
Okay I'm back, what did I miss other than the title change, banner change and et cetera?

**Comment by not-nef** [comment]
Done @sumeshir26

**Comment by not-nef** [comment]
: image

**Comment by im-coder-lg** [comment]
Can you share a transparent one or try using something like Favicon Generator to make the icon?

**Comment by not-nef** [comment]
> Can you share a transparent one or try using something like Favicon Generator to make the icon?

the version on my fork is transparent

**Comment by im-coder-lg** [comment]
Okay will inspect that. After some tests, I say we'll be good to merge the PR(Note to self: DO NOT MERGE THE PR WITHOUT PERMISSION cuz it might happen)

**Comment by im-coder-lg** [comment]
Also, @not-nef can we increase the configuration length by maybe 5 pixels? Will test that and tell the outcome here too.

**Comment by not-nef** [comment]
dunno what that means but ok

**Comment by not-nef** [comment]
merge?

**Comment by im-coder-lg** [comment]
Get your changes on the base branch. That's the way to get your changes to TimerX.

**Comment by not-nef** [comment]
woah, im a contributor lesgo

**Comment by im-coder-lg** [comment]
Congrats bro! I recommend you search for more features to add, then open an issue and then, go ahead with a PR! Would love to see more contributions from you and I'd love to review them!

**Comment by not-nef** [comment]
i think ill get my hands on a settings page next

**Comment by im-coder-lg** [comment]
Ah, we are aiming for the same thing! Let's use the configurator file for the same work.

**Comment by not-nef** [comment]
ok, gonna start in an hour or so

**Comment by im-coder-lg** [comment]
I kinda think @sumeshir26 finished the settings part(there's a settings branch) but I need _you_ to test it, and improve it like modifying the sizes, locking maximization and more.

**Comment by im-coder-lg** [comment]
Then, we can open another PR to the settings branch to get your changes there.

**Comment by sumeshir26** [comment]
No, it’s not finished, tos
Day only I added

**Comment by im-coder-lg** [comment]
Well, an about page?

**Comment by im-coder-lg** [comment]
That needs some extensive code to add links, an Ok button and more, right?

**Comment by not-nef** [comment]
@im-coder-lg i checked the settings branch and it literally contains nothing (only a label and some theme config) so i will recode the page

**Comment by not-nef** [comment]
> That needs some extensive code to add links, an Ok button and more, right?

shouldnt be too hard

**Comment by im-coder-lg** [comment]
Ok, looking forward to the PR! 😁

**Comment by sumeshir26** [comment]
Locallay, I have gotten far on the settings page. I recebtly added sving to json fies nef could work

**Comment by sumeshir26** [comment]
on the about page

**Comment by not-nef** [comment]
i will still do a recode, i have an idea in mind

**Pull request merged**
