### PR TITLE
feat+fix:cx_Freeze, Actions, etc.

### LINKED ISSUE #5: [Bug 🐛 ]: Github Actions
So, let's get straight to the point.
We both have a Windows computer, so even if I switch to Linux(not yet, I need to give my PC, maybe by Saturday, I hope so), you can test Windows. We know that Mac and Linux use the `bash` shell. Well, Mac uses Zsh, but the set of commands are awfully similar.
So, this is my idea. If the shell works, it could mean that the OS build also would work.
About the .App Mac executable, we'll see about that later, we can NOT access the runtime that GitHub Actions uses to upload the build.
So, we need a build converter of sorts. I can run only server VMs, so we could run a VM or we could try finding any Mac runtimes on the cloud.
Here's about the build issue(I need to stop diverting the topic):
Windows works
Linux must be working, I'll check Raspbian(PS: It's Debian, not Ubuntu)
Mac, we must inspect.
For the Mac App file, we must inspect that.
Linux AppImage file needs to be created.
An installer file must be made, where the modules are installed automatically. We could use the .BAT file for Windows(DOS coding :sunglasses:) or .SH coding for Mac and Linux.
So, the installer is done, it will build the program from source so users don't miss anything.
About the runtime, remove Windows and Mac. Let Linux be there, once we find a Mac fix, we can add a separate build file for Mac. You can manage Windows, it's a matter of five minutes to build.
If I am confusing enough, I'm sorry. Got a whole lot of things around me, this one dominating them.

### PR DESCRIPTION
**Pull request by im-coder-lg**
yes, we did it
Success! Raw logs: https://pipelines.actions.githubusercontent.com/m6uqHNCtCOVuhJiAJ3KWo8a4OKe5xHQUII9SafEtrG12bZTpyc/_apis/pipelines/1/runs/11/signedlogcontent/2?urlExpires=2021-12-04T10%3A12%3A49.1060900Z&urlSigningMethod=HMACV1&urlSignature=O6FJk3AtUZhbTwCUqVxO%2FMDtJNsX%2F6TT4MX4JYOiVxI%3D
[Build Workflow](https://github.com/im-coder-lg/TimerX/actions/workflows/main.yml)
We need to add Ubuntu and Mac soon.
Closes #5

### CODE REVIEW

**Comment by not-nef** [comment]
gg, still need a tester?

**Comment by im-coder-lg** [comment]
Yup! To check if the GUI loads+installer test for Macs, etc.

**Comment by im-coder-lg** [comment]
Release workflow works, it drafts a release, you can edit via the web client on mobile/desktop. 
We fixed _everything_ related to Windows builds. Now, I will test macOS and Linux builds.

**Comment by im-coder-lg** [comment]
The build error resides in UBUNTU!!!
That's the error with our actions, Mac and Linux are Unix-like, POSIX-compliant systems. PyInstaller doesn't work well with them, I think I might find a solution.

**Comment by im-coder-lg** [comment]
Something that might seem unrelated: 
> AppImage” file you download them as. Users of macOS will be very familiar with the concept of AppImages as macOS applications are packaged in a very similar way. ... To run an AppImage, simply right-click it, select Properties, go to the Permissions tab and make sure Allow executing file as program is ticked.

We can release one file for two OSes. What do you say?

**Comment by sumeshir26** [comment]
@im-coder-lg Yeah, AppImage for both might work, but is it required to edit the permissions?

**Comment by im-coder-lg** [comment]
Yeah, I guess it sends a `chmod` command since we know that GUIs run on top of CLIs, so toggling+saving that might mean that `chmod` ran. But the hardest question is this: How the heck can we transform the main file into an AppImage? Seems too complex, if you ask me.

**Comment by im-coder-lg** [comment]
And everyone says that PyInstaller creates Mac/Linux binaries. I found one on my Raspberry Pi but couldn't execute it. Maybe it's a bug in the OS. I am hoping to switch to Zorin soon, I want to do it myself but I can't find a competent USB.

**Comment by sumeshir26** [comment]
For now,the current implimentation is fine, appimages can be added after v1.0

**Comment by im-coder-lg** [comment]
Okay :+1: And PS: It's implementation, not implimentation. Just correcting.

**Comment by im-coder-lg** [comment]
Linking PRs.
https://github.com/im-coder-lg/TimerX/pull/2

**Comment by im-coder-lg** [comment]
I have added a set of commits in im-coder-lg#2, mainly a6d5b04, aa0db69, and 26b7003. But still it fails.

**Comment by im-coder-lg** [comment]
Maybe we shouldn't use PyInstaller for Mac and Linux... What should we do?

**Comment by im-coder-lg** [comment]
We could try this: `python ~/.TimerX/code/main.py & && disown`. I found this in another repository, we could use this command to send TimerX into the background. Then, if the user wants to kill the process, they could try closing TimerX. If it lags their computer, they could try `ps all` and find the PID of the Python process.
What do you think about this?
We also need to make sure PyInstaller is sent to the optional requirements file so that if a Windows User wants to build the program, they can get the optional dependencies and build the app from source.

**Comment by im-coder-lg** [comment]
I kinda feel devastated.
How the heck can we build a Python project into a Mac/Linux build, make an installer for all OSes, make sure it downloads and move the files to the AppData/Applications/`/usr` directory and make a shortcut for it?
Research on Google proves absolutely nothing!
Maybe I have an idea, will respond afterwards. Sorry for the million replies, it kinda became a habit for me.

**Comment by im-coder-lg** [comment]
I think the people at PyChess might help. Just opened a ticket there, you can go to PyChess and check that. If you want(if and only if you want), you can try looping in this PR there.

**Comment by sumeshir26** [comment]
@im-coder-lg https://github.com/pychess/pychess/blob/master/create_rpm_py36.sh

**Comment by sumeshir26** [comment]
There are many different files like this for different platforms

**Comment by im-coder-lg** [comment]
Hmm... Seems like you are right...
Let's wait for a moderator to help since a moderator knows better. They could also help us in fixing our GitHub Actions runtime too, right?

**Comment by sumeshir26** [comment]
@im-coder-lg I don’t think anyone will respond since recently the issues have no responses and there are

**Comment by im-coder-lg** [comment]
Hmm... Let's wait for a reply _and_ test this on a Gitpod container. They have good Ubuntu VMs.

**Comment by sumeshir26** [comment]
@im-coder-lg  Don’t add any commits, I found the perfect solution which also adds a shortcut to the start menu… will explain later

**Comment by im-coder-lg** [comment]
Okay, I found some merge errors on the Mac/Linux test branch, so now is the time to comment out the Blur code, use the triple apostrophe method to comment them out, mark them as optional features. If not, try making the blur exclusively to Windows using the system platform code.

**Comment by sumeshir26** [comment]
@im-coder-lg What do you think about Cx_freeze? Using the bdist_msi option, we can even create a real installer that adds it to the start menu and puts it in the AppData/TimerX-v1.0 folder.

**Comment by im-coder-lg** [comment]
I haven't heard of it. Hey, wait, go a little bit slow, first, comment out the blur or add it to the platform detection code to Windows, then I will research on Cx_freeze and learn how to use the tool. After that, you add the code and I'll try adding it to `release.yml` and we shall go ahead with merge once I give the go-ahead.

**Comment by im-coder-lg** [comment]
Cx_Freeze seems trustworthy, link to setup.py Documentation:  https://cx-freeze.readthedocs.io/en/latest/setup_script.html

**Comment by im-coder-lg** [comment]
Hey, @sumeshir26 I created an issue at the cx_Freeze repo on help. Like our `main.spec`, they have `setup.cfg` and also they support macOS DMG installers. So I asked for help on creating them+also trying to make an AppImage, it works for almost every Linux distros(universal). So let's wait for the reply while simultaneously testing cx_Freeze.
If the maintainer asks for the project link, can I give the TimerX repo link? That has been bothering me for a long time(I didn't link TimerX on the PyChess issue due to this), so just wanna confirm.

**Comment by sumeshir26** [comment]
@im-coder-lg Sure, give the link, I don’t mind. (That literally means more people see timerX)

**Comment by im-coder-lg** [comment]
Fixed+modified some data, is the upcoming release v0.2? Also, don't forget to mark 0.1's release on GitHub as a pre-release.

**Comment by sumeshir26** [comment]
> Fixed+modified some data, is the upcoming release v0.2? Also, don't forget to mark 0.1's release on GitHub as a pre-release.

Nope, v1.0-alpha

**Comment by im-coder-lg** [comment]
@sumeshir26 Let's just use Windows checks for now. Since we are creating a `.dmg`(@not-nef need your help on testing the disk image installer!), we have a tester. After @not-nef reports back, we have some choices. The most probable one is the installer succeeded. But if it didn't, we must ask for a macOS Catalina+ tester. I am sure it has to succeed on High Sierra.
Also, we could ask users to use the Wine emulator till we have a (working) Linux AppImage. Hmm :thinking: My thought is this:
In a project named code-server(now you know what I do half of the time on GitHub), I actually contributed there for creating a banner, which is just a 1x1 markdown table. Looks like this:
```markdown
| {{your-text-here}}
| ---
```
Preview:
| {{your-text-here}} text: This is TimerX Beta
| ---

---

We could use that and make a banner asking Linux users to use Wine till we create an AppImage.
> Nope, v1.0-alpha

Sorry, was typing this when you sent(took a long 5 minutes). I will add it to `setup.py` soon.

**Comment by im-coder-lg** [comment]
Correction: Wine is a compatibility layer, not an emulator.

**Comment by im-coder-lg** [comment]
> Instead of using code-server try using vscode.dev

I use vscode.dev if I am in sudden urgency, but the power of code-server is that it runs your usual VS Code IDE on your browser. It allows access to your local terminal(xterm.js) and it's a big project. Really really big. I helped them get a banner to differentiate between their enterprise product(paid subscription after 60 days, kinda hard to set it up) so I know the banner thing. Point is, I am not emphasising on code-server right now. I am telling you that until we add DEB/RPM, we have to tell people to use the WINE(Wine Is not An Emulator, literally meaning that) compatibility layer and install the Windows version until DEB/RPM(please add AppImage so that Arch Linux users don't feel left out) releases are out.

**Comment by im-coder-lg** [comment]
Did you test it on Gitpod/your WSL instances?

**Comment by sumeshir26** [comment]
@im-coder-lg I'll try that before merging...

**Comment by im-coder-lg** [comment]
I will also test, so I will know how this works.

**Comment by sumeshir26** [comment]
@im-coder-lg You posted the comment in the wrong repo!

**Comment by im-coder-lg** [comment]
> We need some more time before merging. I'll give the go-ahead once everything is clear.

Yeah lolz that's the problem with multiple pinned tabs, I hate them disappearing.

**Comment by im-coder-lg** [comment]
I like this kind of code(half of it is commented out since I need help in understanding the `setup.py` syntax.
```python

import sys
from cx_Freeze import setup, Executable

# need help, so don't remove this code!
# directory_table = [
#     ("ProgramMenuFolder", "TARGETDIR", "."),
#     ("MyProgramMenu", "ProgramMenuFolder", "MYPROG~1|My Program"),
# ]

# msi_data = {
#     "Directory": directory_table,
#     "ProgId": [
#         ("TimerX", None, None, "A simple, lightweight, & beautiful timer app built in Python and tkinter.ttk using rdbende's Sun Valley TTk Theme", "IconId", None),
#     ],
#     "Icon": [
#         ("IconId", "assets/icon.ico"),
#     ],
# }

# bdist_msi_options = {
#     "add_to_path": True,
#     "data": msi_data,
        
# }

# build_exe_options = {"excludes": ["tkinter"], "include_msvcr": True}

executables = [
    Executable(
        "main.py",
        copyright="MIT License",
        base=base,
        icon="assets/icon.ico",
        # commented out, need help on this
        # shortcutName="TimerX",
        # shortcutDir="MyProgramMenu",
    ),
],

setup(
    name="TimerX",
    version="v1.0-alpha",
    description="A simple, lightweight, & beautiful timer app built in Python and tkinter.ttk using rdbende's Sun Valley TTk Theme",
    executables=executables,
    options={
        "build_exe": build_exe_options,
        "bdist_msi": bdist_msi_options,
        "bdist_dmg": bdist_dmg_options,
    },
)
```
Sorry for the long code, but I think this allows better customisation and control.

**Comment by im-coder-lg** [comment]
Let the PR be open for now, let's wait for the reply or if it doesn't arrive, we can start fiddling with the code to learn the inputs.

**Comment by im-coder-lg** [comment]
Some links: Mac build:
https://pythonschool.net/pyqt/distributing-your-application-on-mac-os-x/
Linux+Windows build:
https://subscription.packtpub.com/book/application-development/9781849513845/1/ch01lvl1sec11/make-a-compiled-executable-under-windows-and-linux
Forgot to send this.
Also, I got a response(mentioned the PR there), we could use the PyQt5 sample for Windows MSI and Mac DMGs.
Kinda looks like this:
https://github.com/marcelotduarte/cx_Freeze/blob/3d23dbfbc19acb5858638a8adba7d15512f29939/cx_Freeze/samples/pyqt5/setup.py#L35-L63
We could use that code for making the DMGs. Also RPMs are supported. I wonder if DEB is tho...

**Comment by im-coder-lg** [comment]
We could use the samples: https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples
That has a lot of examples and the PyQt5 one kinda seems best. @marcelotduarte(pinging you so that you can use this PR's base branch, not the one it's getting merged into) said that we could use the PyQt5 even though he knows we use Tkinter.
So, we got some code. Now, we have to wait. Also, almost kinda forgot, thanks for your help @marcelotduarte!

**Comment by im-coder-lg** [comment]
We should add `bdist_rpm` too. I bet the PR will be merged by Sunday.

**Comment by im-coder-lg** [comment]
Let's test the `bdist_rpm` on Ubuntu. I hope it creates a DEB too.

**Comment by im-coder-lg** [comment]
Doesn't work. I think we'll give `.tar.gz` tarballs so that users can unzip it through the `tar` cli and use it until we find a stable method to add RPM. Removing the change!

**Comment by im-coder-lg** [comment]
In the cx_Freeze docs(link here: ), it's stated that:
> For a more advanced Windows installer, use a separate tool like Inno Setup to package the files cx_Freeze collects.

I will test that for `.tar.gz` files. Maybe we could merge it after `.tar.gz`, presumably by Sunday(I hope so)

**Comment by sumeshir26** [comment]
@im-coder-lg I just need a upgrade id before merging...

**Comment by im-coder-lg** [comment]
What does that do?

**Comment by sumeshir26** [comment]
> What does that do?

When updates are published, it replaces the current start menu shortcut and program files folder.

**Comment by im-coder-lg** [comment]
Also, we need to add tarball support so that Linux users just unzip it and execute the app.

**Comment by sumeshir26** [comment]
@im-coder-lg Try the msi now... it almost works for me. Does it work for you?

**Comment by im-coder-lg** [comment]
> Try the msi now... it almost works for me. Does it work for you?

Testing it, what's wrong, you said "almost"?

**Comment by im-coder-lg** [comment]
Encountered error code 2756.

**Comment by im-coder-lg** [comment]
[TimerX-win64.zip](https://github.com/sumeshir26/TimerX/files/7683238/TimerX-win64.zip)
The unzipped version in the `build/` works tho, uploading zipfile here.

**Comment by sumeshir26** [comment]
Hurr... Apparently it just copies the files from the build to the dist. No idea why this hapens..
Now also would be time

**Comment by sumeshir26** [comment]
the time to start on the action for Windows and Mac. Lets wait on the linux file. And did you try `python setup.py build` on ubuntu?

**Comment by im-coder-lg** [comment]
No, not yet.

**Comment by im-coder-lg** [comment]
Can you test bc16754 on the fork's Actions tab? Wanna make sure it works.

**Comment by sumeshir26** [comment]
@im-coder-lg Alreaday on it...

**Comment by sumeshir26** [comment]
@im-coder-lg Hmmm. it doesn't draft a realease

**Comment by im-coder-lg** [comment]
brb

**Comment by im-coder-lg** [comment]
There was a draft of release v1.0.0 on my fork(10 minutes ago), have you checked that?
Update: Drafted, it needs at least 2 minutes to deploy. Are you able to form DMGs successfully?

**Comment by im-coder-lg** [comment]
I wonder if we could add multiple files, that'd be effective, right?

**Comment by im-coder-lg** [comment]
I removed the draft release since it's useless on my fork, but we have the runtime logs, so we are good on the release part, next is to find out how to attach multiple files to the release drafter(coincidentally, there's a GitHub app called `release drafter`, it does this job effectively than ours since we can address changes automatically in that. Minus is, it doesn't add the files).

**Comment by sumeshir26** [comment]
@im-coder-lg Can you make sense of this: https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/ ?
If, yes can you apply those changes here?

**Comment by im-coder-lg** [comment]
I kinda get it, will start working on it.

**Comment by sumeshir26** [comment]
@im-coder-lg Thanks!

**Comment by im-coder-lg** [comment]
Making the entire action part in another branch, so that this will be in the safe zone. I will check if it works, and then create a PR to the `actions-fix` branch, so you'll have to merge only one PR.

**Comment by im-coder-lg** [comment]
I can't understand this! I wish it was a little bit more detailed. For now, let's use the Windows and macOS parts. After that, I'll try packaging TimerX into a tarball so that Linux users can move it into the `/usr` directory, refresh the shell, and run TimerX from that. After that, we'll find out how to create shortcuts on the application menu and we are in luck.

**Comment by im-coder-lg** [comment]
Or, let's try this. We'll remove the release workflow, you install the Release Drafter app from the Marketplace, allow it access to this repo. I will create its config. Then, after the merge, whatever changes you push, it updates the draft all the time. So, it's easy for you to create the release. @not-nef can you install Anaconda3, get cx_Freeze and the packaging requirements and help us on creating the DMGs?
If you can, great! @sumeshir26 @not-nef said he can access his computer during the holiday, so we'll release the alpha version during the holiday time(preferably 20-30 Dec). By that time, @not-nef needs to create the DMG, put it in a RAR/ZIP format(only those formats, preferably RAR), upload it here. @sumeshir26 can unzip the file while also creating a packed+unpacked(in case they weren't able to install it) and we can get the Alpha version during that time.
Once you install the app, ping me. I will clean up some clutter, add the macOS Builds(if it isn't added yet) to the updated actions file, add the drafter bot's config, and give the go-ahead for merge. Then, I will create a discussion to prepare for Alpha and we can send DMGs(not DMs) and get 1.0.0-alpha released!
This seems to be the best solution till we understand the Release Workflow syntax.

**Comment by im-coder-lg** [comment]
If you didn't understand, I will provide a step-by-step guide for this, not here, but in GitHub Discussions(keeping this clean for the meantime).
@not-nef need your help as soon as possible!

**Comment by sumeshir26** [comment]
@im-coder-lg OK

**Comment by im-coder-lg** [comment]
Your suggestion was good, but it seems like only GH Actions professionals can understand that. It wasn't a step-by-step guide and there was no final code viewing, so that is hard to do. But mine seems kinda better, although you need to do some work like downloading, extracting, etc.

**Comment by im-coder-lg** [comment]
Initiating test!

**Comment by im-coder-lg** [comment]
Windows-success
Mac-file naming error.

**Comment by sumeshir26** [comment]
@im-coder-lg Wait... Fixing error

**Comment by im-coder-lg** [comment]
Sorry, I pushed the change :( but I think it's fixed

**Comment by sumeshir26** [comment]
@im-coder-lg Run it!

**Comment by im-coder-lg** [comment]
Test initiating

**Comment by sumeshir26** [comment]
@im-coder-lg It seems to be running the build on the master branch. Can you run on actions-fix?

**Comment by im-coder-lg** [comment]
Give me a minute, Vivaldi kinda slowed down.

**Comment by im-coder-lg** [comment]
You did a mistake, maybe you added the Windows MSI on the Mac build.
I think it doesn't work like that, fixing that.

**Comment by im-coder-lg** [comment]
I'll fix this later, too confused with this. Maybe I got an idea coming up... What do you think of this:
Windows and macOS create separate release drafts.
You can download the draft release's binary installers, the MSIs and DMGs and re-upload it into your version of the release since there's actually _no_ way we can combine releases like linking two OSes together.

**Comment by sumeshir26** [comment]
@im-coder-lg That might work...

**Comment by im-coder-lg** [comment]
Yup, that might work...

**Comment by im-coder-lg** [comment]
I will work on this after some time.

**Comment by sumeshir26** [comment]
@im-coder-lg You know what, to improve my actions skills, I will try to work on this myself.

**Comment by im-coder-lg** [comment]
Remember to add the workflow dispatch code too!

**Comment by sumeshir26** [comment]
@im-coder-lg Run the mac workfow

**Comment by im-coder-lg** [comment]
2 minutes, starting Chrome up, Vivaldi again slowed down(resource hogged)

**Comment by im-coder-lg** [comment]
There is no `workflow_dispatch` section! Did we create a glitch?

**Comment by sumeshir26** [comment]
@im-coder-lg Moving to #9

**Comment by im-coder-lg** [comment]
Got the mail, writing a comment there!

**Pull request closed without merging**
