### PR TITLE
Settings window

### PR DESCRIPTION
**Pull request by not-nef**
THIS PR IS NOT READY FOR MERGING, its just for progress tracking.

Check this out:

Screenshot 2021-12-25 134506
Screenshot 2021-12-25 134533
:

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Woah, is that Windows 11? Cool!
I got some reviews for you, they are coming! Also, this best be merged to the settings branch so that it's kinda easier to revert back when everything gets messed up.

**Comment by im-coder-lg** [comment]
Also, too much of additions, wonder if we could merge this...

**Comment by not-nef** [comment]
> Also, too much of additions, wonder if we could merge this...

wdym too much additions?

**Comment by sumeshir26** [comment]
could you replace the current dark theme bhutton with the settings one?

**Comment by not-nef** [comment]
> could you replace the current dark theme bhutton with the settings one?

sure

**Comment by sumeshir26** [comment]
Here are the things that should be added to the settings window
- Theme
- Slider for transperency
- Option to play sound after timer ends
- Option to send notification
- JSON or YAML sefttings saving

**Comment by not-nef** [comment]
TODOS:

1. Make sure that icons get synced
2. Add option to pin / unpin
3. Add labels and icons
4. Position everything so it doesnt look absolutely stupid

**Comment by not-nef** [comment]
5. everything sumeshir mentioned above

**Comment by not-nef** [comment]
@sumeshir26 wdym json and yaml setting saving? i just did it with a text file.

**Comment by sumeshir26** [comment]
Then we need to have like 10 text files. You can do it woth txt files, I will migrate to Json afterwards

**Comment by not-nef** [comment]
just tell me how to do it

**Comment by im-coder-lg** [comment]
> Option to play sound after timer ends

This doesn't seem to work on my Windows 7 PC as well as my Raspberry Pi running Ubuntu Impish. Need to inspect this.

**Comment by im-coder-lg** [comment]
> JSON or YAML sefttings saving

Let's use YAML, it doesn't have a lot of curly braces that confuse me.

**Comment by not-nef** [comment]
now button texture syncs

**Comment by not-nef** [comment]
i will continue tomorrow

**Comment by not-nef** [comment]
Makin Progress :)

**Comment by sumeshir26** [comment]
Great work so far!

**Comment by not-nef** [comment]
btw @sumeshir26 we can do it with one text file if we only read specific lines, so you dont have to migrate it.

**Comment by sumeshir26** [comment]
Okay, do it how you think is best...

**Comment by not-nef** [comment]
thx

**Comment by not-nef** [comment]
bro this took ages

**Comment by not-nef** [comment]
@sumeshir26 what transparency do you mean?

**Comment by im-coder-lg** [comment]
Hey I'm back, need to test this soon. Can I change the base branch to the `settings` branch? Might make it kinda more easy, right?

**Comment by im-coder-lg** [comment]
I can't explain tho, feeling blank on the branch change. Maybe not.

**Comment by not-nef** [comment]
@im-coder-lg i would keep it like it is and then merge it in the master branch when its done.

**Comment by sumeshir26** [comment]
By transperency I mean app.attributes('alpha', 0.%), look it up, will need a slider for that

**Comment by not-nef** [comment]
ok, will do that

**Comment by im-coder-lg** [comment]
> By transperency I mean app.attributes('alpha', 0.%), look it up, will need a slider for that

But for that, you need to put limits, right? Why not 1/4(25/100)?

**Comment by not-nef** [comment]
@sumeshir26 app.attributes("-alpha", .5) will make the window and all elements (+ the titlebar) transparent. Do you really want that?

and @im-coder-lg ofc we have to put a limit or you could make the window invisible

**Comment by im-coder-lg** [comment]
> ofc we have to put a limit or you could make the window invisible

Let's make it 1/4 or 1/5, meaning 25/100 or 20/100 in terms of percentage.

**Comment by im-coder-lg** [comment]
> @sumeshir26 app.attributes("-alpha", .5) will make the window and all elements (+ the titlebar) transparent. Do you really want that?

I think I read in the readme that there's a task to make the titlebar kind of invisible. Maybe I am wrong tho...

**Comment by im-coder-lg** [comment]
Configurator theme doesn't sync up :(

**Comment by im-coder-lg** [comment]
Also, the Always on top button seems to go to light mode icons once activated in Dark mode.

**Comment by sumeshir26** [comment]
No need for a aleays on top button...

**Comment by sumeshir26** [comment]
@not-nef I meant an slider which controls the alpha value

**Comment by not-nef** [comment]
> @not-nef I meant an slider which controls the alpha value

yea, but the alpha value makes the whole thing transparent

**Comment by not-nef** [comment]
> Configurator theme doesn't sync up :(

oh fu

**Comment by not-nef** [comment]
will fix asap

**Comment by im-coder-lg** [comment]
> oh fu

Fortunately no swearing! Any ideas on fixing this? I think you can just link settings to configurator.

**Comment by not-nef** [comment]
> > oh fu
> 
> 
> 
> Any ideas on fixing this?

i just did (2 lines of code lmao)

**Comment by not-nef** [comment]
there it is

**Comment by not-nef** [comment]
> > > oh fu
> > 
> > 
> > 
> > Any ideas on fixing this?
> 
> i just did (2 lines of code lmao)

well actually 4

**Comment by not-nef** [comment]
Check this out @sumeshir26 

https://user-images.githubusercontent.com/83908932/147456761-320b422f-a2b2-4530-992f-85b9475c3fa3.mp4

**Comment by sumeshir26** [comment]
Perfect!

**Comment by not-nef** [comment]
still having some trouble with saving the value

**Comment by sumeshir26** [comment]
You could save the config in a dictuonary and then save it to a json file using json.dump().On next launch the config file can be readed using json.load()

**Comment by not-nef** [comment]
LETS F GOO

**Comment by not-nef** [comment]
> You could save the config in a dictuonary and then save it to a json file using json.dump().On next launch the config file can be readed using json.load()

Nah, saving and loading wasnt the problem, it just tried to set a .x value to a slider which just doesnt work. its fixed now

**Comment by im-coder-lg** [comment]
Is this ready to be merged too?

**Comment by not-nef** [comment]
definetely not

**Comment by not-nef** [comment]
Btw what in gods name is that sound that plays when finishing

**Comment by not-nef** [comment]
its horrible

**Comment by im-coder-lg** [comment]
Idk bro my driver's incompatible 😂 but I wonder if we replace it with another one.

**Comment by sumeshir26** [comment]
> its horrible

I Know, definitely tell me if you find a better sound😂

**Comment by im-coder-lg** [comment]
I think I might have an idea. There's an app for Android called AirDroid. I once installed it and accessed the web version of the app. Over there, there's a shortcut for ringtones. You could get an alarm ringtone of your choice, get the .ogg file and convert it to .wav, how's the idea? It's best to do on an Android phone since it's easily hackable but AirDroid doesn't need root access. Maybe I could try on my phone, it has a nice timer beep that lasts for maybe 1 second.

**Comment by not-nef** [comment]
@sumeshir26 i need some help with the checkbutton. Can you help?

My Code:

```
output_var = tkinter.StringVar()

btn1 = ttk.Checkbutton(settings_window, variable = output_var, onvalue="yes", offvalue="no")
btn1.pack()
```

if the button is checked, `output_var` should be "yes", if its unchecked it should be "no". But its always empty, no matter if the button is checked or unchecked. What did i do wrong?

**Comment by im-coder-lg** [comment]
How about an if else condition? If clicked then?

**Comment by not-nef** [comment]
well, but how do you check the state? we must know if its enabled or not

**Comment by sumeshir26** [comment]
Use .state()

**Comment by not-nef** [comment]
Icons and proper descriptions next

**Comment by not-nef** [comment]
@sumeshir26 where did you get the icons for TimerX?

**Comment by sumeshir26** [comment]
fluenticons.co

**Comment by not-nef** [comment]
anyone know why my pfp on the commits doesnt update?

**Comment by sumeshir26** [comment]
It does for me

**Comment by im-coder-lg** [comment]
Guys, how's it going here? Also, #26 is almost ready for merge, didn't see any replies for the last two days too.
@not-nef the transparent part works well. Actually, too well. It confused me between the configurator window and main window, the configs didn't kinda work on the configurator. Anyway, this is cool. What else are you going to add?

**Comment by not-nef** [comment]
wdym the configs dont work in the configurator? And theres not much left actually!

**Comment by im-coder-lg** [comment]
image
Can you fix this bug?
And before you ask, yeah, Windows 7 `:(`

**Comment by not-nef** [comment]
oh, forgot to mention @im-coder-lg you have to delete your previous config file. (its not actually a bug because it wont encounter for the end-user)

**Comment by im-coder-lg** [comment]
me: slaps myself on my forehead.
I will try again!

**Comment by im-coder-lg** [comment]
Oh yeah is this a bug kinda since if you get to the lowest levels of transparency, you lose control of the wndow, is it known?

**Comment by im-coder-lg** [comment]
Also, configurator doesn't get synced up with transparency tho...

**Comment by im-coder-lg** [comment]
Request to add this to gitignore:
<details>
<summary>Code, shortened for no spamming</summary>
<section>

```diff
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
pip-wheel-metadata/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
./.vscode
./.__pycache__/*
./__pycache__/*

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
.python-version

# pipenv
#   According to pypa/pipenv#598, it is recommended to include Pipfile.lock in version control.
#   However, in case of collaboration, if having platform-specific dependencies or dependencies
#   having no cross-platform support, pipenv may install dependencies that don't work, or not
#   install all needed dependencies.
#Pipfile.lock

# PEP 582; used by e.g. github.com/David-OConnor/pyflow
__pypackages__/

# Celery stuff
celerybeat-schedule
celerybeat.pid

# SageMath parsed files
*.sage.py

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/

+++ # Config
+++ config/*
```

</section>
So that config doesn't disturb git pulls.

**Comment by not-nef** [comment]
> Oh yeah is this a bug kinda since if you get to the lowest levels of transparency, you lose control of the wndow, is it known?

i limited the slider to 25 so this shouldnt happen

**Comment by not-nef** [comment]
> Also, configurator doesn't get synced up with transparency tho...

will look into that after icons and description

**Comment by not-nef** [comment]
> Also, configurator doesn't get synced up with transparency tho...

weird, it does for me, can you tell me steps to reproduce?

**Comment by im-coder-lg** [comment]
> /ping @im-coder-lg does that work? lmao

What?
> weird, it does for me, can you tell me steps to reproduce?

Just run the main.py file from terminal.
Maybe it's due to OSes.

**Comment by not-nef** [comment]
>What?

that /ping thing

**Comment by not-nef** [comment]
saw you do it

**Comment by im-coder-lg** [comment]
> that /ping thing

Oh, that huh... The usage is fairly simple. You ping a user, right? The `/ping` is just an extension, the mention does the job. But the reason I use the pings is so that the person I pinged would know that it's just a ping. Neat trick to do.

**Comment by not-nef** [comment]
@sumeshir26 need help again! i try to make a label with an image

Code: 

```
img = PhotoImage(file="./assets/images/dark/speaker.png")

img_holder = tkinter.Label(settings_window, image=img)
img_holder.pack()
```

it throws me the following error:

```
image "pyimage9" doesnt exist!
```

What does that mean and how do i fix it?

**Comment by im-coder-lg** [comment]
There is no response from @sumeshir26 yet, have you tried renaming the function or atleast imported the right module?

**Comment by not-nef** [comment]
what function should i rename and yes i imported the right module

**Comment by im-coder-lg** [comment]
Did you atleast use the right tag?

**Comment by sumeshir26** [comment]
https://stackoverflow.com/questions/50012062/when-using-tkinter-error-tclerror-image-pyimage8-doesnt-exist

**Comment by not-nef** [comment]
ive found a fix!

**Comment by not-nef** [comment]
> https://stackoverflow.com/questions/50012062/when-using-tkinter-error-tclerror-image-pyimage8-doesnt-exist

oh, yep thats the one i found

**Comment by sumeshir26** [comment]
@not-nef Can you give me collaborator access to your fork?

**Comment by not-nef** [comment]
Its done.
Screenshot 2021-12-31 145220

**Comment by not-nef** [comment]
@sumeshir26 gave you acces, but this pr is ready for merging

**Comment by im-coder-lg** [comment]
Bro remove configurator.py from setup.py!!! cx_Freeze is failing!

**Comment by im-coder-lg** [comment]
I'll commit that

**Comment by im-coder-lg** [comment]
Fixed.

**Comment by not-nef** [comment]
how did you commit?

**Review by im-coder-lg — APPROVED** [review]
I finally declare LGTM! Congrats @not-nef!

**Comment by not-nef** [comment]
np, this was a fun journey!

**Comment by not-nef** [comment]
@sumeshir26 merge?

**Comment by im-coder-lg** [comment]
> how did you commit?

Collaborator access you gave me. It was of real value.

**Comment by im-coder-lg** [comment]
> np, this was a fun journey!

yeah too fun
> @sumeshir26 merge?

On New Year. That'd make it crazily special. We'd better merge #26 too, a lot of additions that's why.

**Comment by not-nef** [comment]
coolio, gettin pretty close to 1.0 right?

**Comment by im-coder-lg** [comment]
Actually, it's 0.9 right now but it might change anytime!

**Comment by sumeshir26** [comment]
@not-nef Can you share a final screenshot?

**Comment by not-nef** [comment]
> Its done.
> 
> Screenshot 2021-12-31 145220
> 
> 

@sumeshir26

**Comment by sumeshir26** [comment]
@not-nef Thank You!

**Comment by not-nef** [comment]
LETS GOOO

**Comment by not-nef** [comment]
@sumeshir26 is there some way to apply for collaborator acces?

**Comment by im-coder-lg** [comment]
Only the maintainer can give collaborator access. But you have to be careful, 'cause you might end up doing some mistakes, that's why I use PRs for new things on the website and immediate commits to fix simple things like CI/CD.

**Comment by not-nef** [comment]
i would use prs too but it would be cool to have collaborator acces for things like #28

**Pull request merged**
