### PR TITLE
feat: Unified action

### PR DESCRIPTION
**Pull request by sumeshir26**
@im-coder-lg Can you look over the new action which I made which builds for all platforms in one action?
Also, where do you even see draft releases?

### CODE REVIEW

**Comment by im-coder-lg** [comment]
In the releases page. If you want, modify the url to https://GitHub.com/sumeshir26/TimerX/releases

**Comment by im-coder-lg** [comment]
Idk haven't checked yet but will soon.

**Comment by im-coder-lg** [comment]
@sumeshir26 after a long day, I can say it works. I also broke TimerX by spam-clicking the Play button. The resultant output you'd get is this:
If you started spamming immediately, 4 and 3 will be flickering, same everywhere.
I have officially done my first break an app. This is a serious glitch. Imagine a 9-year old kid spamming the Play button and eventually breaking the entire app? Kinda feels like that now.
Also, I have told you about this many times(am I sounding annoyed? If I am, I am not) but you need to check the Play button since by double-clicking it seems to activate the timer, not single-clicking it.
Can you configure the clicking part soon? Also can you find a breakthrough that makes TimerX glitch-resistant to flickering seconds that make your timer endless?

**Comment by sumeshir26** [comment]
@im-coder-lg The double clickimg is fixed on nef's fork, accidentaly pushed it to thewrongfork. It was canuse by the timer_paused var to be incorrectly set to true on startup.

**Comment by sumeshir26** [comment]
Also, about the flickering, it seems to be a Tcl/Tk bug, but i'll look into it anyway

**Pull request merged**
