### PR TITLE
About window

### PR DESCRIPTION
**Pull request by not-nef**
Screenshot 2022-01-01 160908

### CODE REVIEW

**Comment by not-nef** [comment]
@im-coder-lg wanna send the readme text?

**Comment by im-coder-lg** [comment]
What text?

**Comment by im-coder-lg** [comment]
Does a7047705a381d3dfdebcfc239c8c53444491aea2 work? Just wanna know!

**Comment by not-nef** [comment]
> What text?

you said you were gonna write a text for the about page

**Comment by not-nef** [comment]
it says there are conflicts. how do i resolve them?

**Comment by im-coder-lg** [comment]
I'll manage that as well as help you.

**Comment by im-coder-lg** [comment]
The thing is, @sumeshir26 added some code that preexisted here, so it asks which change to accept. I need you to get on to VS Code/Gitpod, open the conflicting files and right beside the changes, a faint "Accept" will be displayed. Choose your change and click that link/button(Electron JS) to change that.

**Comment by not-nef** [comment]
What am i supposed to do?
Screenshot 2022-01-04 135342

**Comment by im-coder-lg** [comment]
WHAT HAPPENED? WHERE ARE THE CHANGES? I can fix this, but why'd you close?

**Comment by im-coder-lg** [comment]
And why can't I reopen the PR?

**Comment by sumeshir26** [comment]
He deleted his branch. Not sure why

**Comment by im-coder-lg** [comment]
Merge conflicts? I said I will fix it though... @not-nef are you reopening this?

**Pull request closed without merging**
