### PR TITLE
feat(surprise): Website by Docusaurus

### LINKED ISSUE #23: Request to make a documentation/homepage site using SSGs
We could also use Jekyll that can use Vercel... Let's take Jekyll, that's widely supported and we will use Netlify for the website deployment since it has Netlify CMS that could allow us to edit without going to GitHub.

_Originally posted by @im-coder-lg in https://github.com/sumeshir26/TimerX/issues/21#issuecomment-1000204245_

In another project called Xplorer(it's best to quote this here so that it might help), they use a NodeJS framework called Docusaurus.
SSGs I know:
1. CODEDOC(stands out for documentation and its special Markdown syntax but doesn't work on Netlify, Vercel, etc.)
2. Jekyll(blogs, websites, too much JavaScript)
3. Next.js(too static but fast as lightning)
4. Docusaurus(never tried this from scratch)

Any ideas on other SSGs? No Gatsby since that seems too complex. The font is kinda bad too(no offence gatsby, I like Montserrat).

### PR DESCRIPTION
**Pull request by im-coder-lg**
We got some good progress going on here!
I am using Docusaurus. Yes, the same is being used at Xplorer. I initially took it for a test and it works really well. You have documentation, a beautiful React-based landing page. You got JAMStack as well as Vercel support which has PR previews. Once I got everything good for the initial part, I'll merge this myself and I will take care of the website.
This is for tracking progress(credits to @not-nef for that part, best to keep you all informed too), as well as some other goodies like bonus points, syntax, etc.

So, here are my next steps to do:

- [x] Add favicon(I have a generator tool, but I wonder if we use the TimerX Windows logo)
- [x] Documentation
- [x] Redesign the landing page
- [x] Remove the blog part(yeah it has that too)
- [x] Configure URLs
- [x] I don't know, any ideas?
- [ ] Merge.
- [ ] @sumeshir26 has to do [these tasks](https://github.com/sumeshir26/TimerX/pull/26#issuecomment-1002568863), they are kinda easy, that's how we set up Vercel CDNs(is that what it's called?).

pls ack

Closes #23

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Wait how is it 9008+ additions? Deleting the blog part!

**Comment by sumeshir26** [comment]
Can you share a screenshot?

**Comment by sumeshir26** [comment]
And from now on, only **Squash and Merge** to not spam tens of commits on the main branch

**Comment by im-coder-lg** [comment]
> Can you share a screenshot?

My Gitpod slowed down, it's weird since this never happened to me. I will switch my browser and send the screenshot.
Can you keep the vercel app installed on your account? After merge, we need to deploy there.

**Comment by sumeshir26** [comment]
Okay

**Comment by im-coder-lg** [comment]
image
Link for live preview: https://3000-jade-mandrill-5z10h3jc.ws-us25.gitpod.io/
Keep refreshing tho if you need to see recent changes.

**Comment by im-coder-lg** [comment]
I figured out how to add and customize the documentation.
Also, Docusaurus has special syntax, it looks like this:
```markdown
:::danger <!--can also be tip and adding this on the line becomes the title-->

Content(add the spacing above and below)

:::
```

**Comment by im-coder-lg** [comment]
We are clearly making progress here! @sumeshir26 do you have any kind of idea to compile/transform Markdown to JSX? It turns out that you need to use JS/JSX for the landing page.

**Comment by im-coder-lg** [comment]
Also, I literally tricked Vercel to accept another branch of my fork, so we might be in luck for GitHub edits as of now.

**Comment by im-coder-lg** [comment]
https://docusaurus.io/docs/markdown-features/admonitions
This was the syntax, admonitions. We could use this to show dangerous things a person might end up doing/notes/tips.

**Comment by sumeshir26** [comment]
To convert try demo.showdown.com

**Comment by im-coder-lg** [comment]
I am testing MDX but will look up on that too!

**Comment by im-coder-lg** [comment]
Did you choose the right link? It seems to not exist for me.

**Comment by not-nef** [comment]
> image
> 
> Link for live preview: https://3000-jade-mandrill-5z10h3jc.ws-us25.gitpod.io/
> 
> Keep refreshing tho if you need to see recent changes.

YO WHAAT

**Comment by not-nef** [comment]
epic

**Comment by im-coder-lg** [comment]
Bro that's nothing. Watch me suffer to add just the features! It's JavaScript, I'm not fluent in that! If I try MDX, it fails, so only choice. But anyway that's too epic. I switched workspaces so the only way to see this is after merging. However, you could hack around too.

**Comment by not-nef** [comment]
i just thought its epic to have a homepage for such a small program

**Comment by im-coder-lg** [comment]
Alright @sumeshir26, what are the features I should add? Theming, that'd be one, simplicity can't be, framework, yes and then, some screenshots. Maybe I'll add cross-platform too!

**Comment by im-coder-lg** [comment]
Guys, I am absolutely proud to say that I have successfully redesigned a whole part of the website! We did it!

**Comment by im-coder-lg** [comment]
image
Preview

**Comment by im-coder-lg** [comment]
This is for today. Next, we'll update documentation, add a contributing guide there, add some more screenshots to the homepage and we are good. Let's merge this by today so that Vercel can be set up now.

**Comment by im-coder-lg** [comment]
I apologize for the large changes, it can't be `node_modules` though.

**Comment by im-coder-lg** [comment]
@not-nef need your idea too!

**Comment by im-coder-lg** [comment]
> i just thought its epic to have a homepage for such a small program

Yeah, but I bet within 3 years TimerX will have a lot of modules, files and features so this is good.
There are modes like docs-only, but what good is a documentation if it doesn't have a homepage other than the GitHub repo?

**Comment by sumeshir26** [comment]
Look At the footer. 
Also, if I want to change the Color’s, how do i do that.

**Comment by im-coder-lg** [comment]
> Look At the footer.

Next task found. After that can I merge?

> Also, if I want to change the Colors, how do i do that.

Simple. Inside `./docs/src/pages`, considering you are starting from the root dir, there is a `*.module.css` file. If you modify that, you can change the colors.

**Comment by im-coder-lg** [comment]
Removed that, next one is merging. Wait for some time tho, need to check Vercel.

**Comment by im-coder-lg** [comment]
https://timer-x-fork-test-2-17f7ylv02-coder-lg.vercel.app
Here we gooooo!

**Comment by im-coder-lg** [comment]
Now we are ready for merging.

**Comment by not-nef** [comment]
yo this is great

**Comment by not-nef** [comment]
Should i write a documentation?

**Comment by not-nef** [comment]
or atleast try to lmao

**Comment by im-coder-lg** [comment]
Feel free to! But ofc after merging the PR!

**Comment by sumeshir26** [comment]
Can you put a screenshot which changes with the theme? Just asking

**Comment by sumeshir26** [comment]
Also the icon on the theme switch looks ugly. Is tht possible to remove?

**Comment by im-coder-lg** [comment]
> Also the icon on the theme switch looks ugly. Is tht possible to remove?

I dont know, I never saw the icon except maybe once. I will look up on that.

**Comment by im-coder-lg** [comment]
:bulb: for light, :moon: for dark? Any better ideas?

**Comment by im-coder-lg** [comment]
Also, is the copyright fine or is there any suggestion?

**Comment by im-coder-lg** [comment]
```diff
themeConfig:
  /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
/* code above */
+++      colorMode: {
+++        defaultMode: 'light',
+++        disableSwitch: false,
+++        respectPrefersColorScheme: false,
+++        switchConfig: {
+++          darkIcon: '🌙',
+++          darkIconStyle: {
+++            marginLeft: '2px',
+++          },
          /*
          Unicode icons such as '\u2600' will work
          Unicode with 5 chars require brackets: '\u{1F602}'
          but I don't get the point of unicodes when we have GitHub emojis, right?
          // this is old. lightIcon: '\u{1F602}',
          */
+++          lightIcon: '\u{1F4A1}',
+++          lightIconStyle: {
+++            marginLeft: '1px',
+++          },
+++        },
     },
```
New additions yet to commit, what do you think? Straight from Docusaurus.

**Comment by im-coder-lg** [comment]
I don't see the point of a dark mode icon, it's barely visible for me. Anyway, I'll commit it and test Vercel deployments.

**Comment by im-coder-lg** [comment]
It works _neatly_ with Unicodes! I'm going to ask users to use Compart.com when it comes to editing icon unicodes here.
Ready for merge! Only one last thing to do for me.

**Comment by im-coder-lg** [comment]
Latest: https://timer-x-fork.vercel.app

**Comment by not-nef** [comment]
sick

**Comment by im-coder-lg** [comment]
> sick

yeah too sick as heck(i hate swearing)

**Comment by im-coder-lg** [comment]
/ping @sumeshir26 why aren't you responding at all?

**Comment by im-coder-lg** [comment]
rerequesting review

**Comment by sumeshir26** [comment]
@im-coder-lg wait for a few days

**Comment by im-coder-lg** [comment]
Ah now we got a reply! Check #25 too, @not-nef needs your help.

**Comment by im-coder-lg** [comment]
But I recommend merging this since that'd decrease additions. No idea than that since that'd be better.

**Comment by im-coder-lg** [comment]
Also, a suggestion, we could also use [this](https://vercel.com/design/icons) for icons. I know Vercel'd courve the icons a bit, but I genuinely think the about button icon must come from here.

**Comment by im-coder-lg** [comment]
<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="none" shape-rendering="geometricPrecision" style="color:var(--geist-foreground)"><circle cx="12" cy="12" r="10" fill="var(--geist-fill)"/><path d="M12 16v-4" stroke="var(--geist-stroke)"/><path d="M12 8h.01" stroke="var(--geist-stroke)"/></svg> and <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" shape-rendering="geometricPrecision" style="color:var(--geist-foreground);--geist-fill:currentColor;--geist-stroke:var(--geist-background)"><circle cx="12" cy="12" r="10" fill="var(--geist-fill)"/><path d="M12 16v-4" stroke="var(--geist-stroke)"/><path d="M12 8h.01" stroke="var(--geist-stroke)"/></svg>. how's this?

**Comment by sumeshir26** [comment]
Ok

**Comment by im-coder-lg** [comment]
> Ok

For the SVG or merging? Need some more context.

**Comment by sumeshir26** [comment]
Svg

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Starting the next changes soon.

**Comment by im-coder-lg** [comment]
YOu got Vercel?

**Pull request merged**
