### PR TITLE
Center the announcement

### PR DESCRIPTION
**Pull request by im-coder-lg**
I'd like to know the difference between a normal announcement(btw @sumeshir26 great that you did that!) and the one I modified. I used the `<div>` HTML tag and aligned it to the center(`<div align=center>`) so anything that you type there will be centred. The extra enters are to allow the MD tags, want to know if this is worth being on the main branch.
PS: Some realigning is needed in the README, maybe I could do it now in this PR. Also maybe I'll consider merging both the `` tag and the banner together.

### CODE REVIEW

**Review by not-nef — APPROVED** [review]

**Comment by not-nef** [comment]
i like this because i think the announcement should be the first thing you see imo

**Comment by im-coder-lg** [comment]
A lil' bit more changes needed though. Will do that soon.

**Comment by im-coder-lg** [comment]
I'm done! What do you think?

**Review by not-nef — COMMENTED** [review]
I would put the announcement under the title, how it was before. but if you think this is better, i approve

**Comment by im-coder-lg** [comment]
Hmm, do people really read the Readme? I think half would need a quick abstract of the project, so that's why I kept it on the top, nvm need @sumeshir26's review on this. But my initial idea was to make users know that v0.9 is out and users can get it by visiting the link given, so what do you think about my idea?

**Comment by not-nef** [comment]
Well i do read the readme, to see if the project interests me. But ok.

**Review by not-nef — APPROVED** [review]

**Comment by im-coder-lg** [comment]
> Well i do read the readme, to see if the project interests me. But ok.

I was thinking from a novice user's perspective. They'd want a quick install, so I prioritised that.

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Squash and merge? Might be better.

**Pull request merged**
