### PR TITLE
Just a command runner

### PR DESCRIPTION
**Pull request by im-coder-lg**
My new feature. @not-nef if you want, I'll make it even for Txt2.

Just is a command runner, like GNU Make, but easier and even with Windows support(make sure you have Git Bash too, it needs `sh`), so we can now just run simple commands than a long command.

If you want, I can add more scripts(or recipes) too.

Just: https://just.systems

### CODE REVIEW

**Comment by im-coder-lg** [comment]
And gradients for the site are not inbuilt, we need custom CSS.

**Comment by im-coder-lg** [comment]
This needs more work with PowerShell and Bash.

**Comment by sumeshir26** [comment]
NICE!

**Comment by not-nef** [comment]
What command is it supposed to run?

**Comment by im-coder-lg** [comment]
Check the Justfile on my branch!

**Comment by sumeshir26** [comment]
@not-nef you need to install Just, which is a reallay powerfull command runner. I find it reallay usefull since I made a just script to build a exe

**Comment by im-coder-lg** [comment]
And it works even on Windows, so it's universal. Make sure you have Git Bash, Just needs a `sh` shell to work.

**Comment by not-nef** [comment]
Cool! I dont really see any use for it in txt2. I can just have my batchfile execute the one thing i need which is compile an exe

**Comment by im-coder-lg** [comment]
Yeah, but you can't keep it for long, right? If Txt2 reaches prod, you have to make sure the repo is clean, right? One file to manage all builds would be better than multiple compilation files that should be in the `ci` folder.

**Comment by im-coder-lg** [comment]
Also, guys I think PyInstaller works properly now. The only issue is that even if Tkinter is installed on macOS or Linux, it doesn't recognize the module. It is rather, a system-level issue or an upstream issue, and since cx_Freeze seems to cause us a bit of inconvenience, I think it's time to jump boats.

I will, of course find a roundabout to use PyInstaller builds successfully on Macs and Linux PCs. Till then, it's best we use PyInstaller for Windows.

**Comment by not-nef** [comment]
Yeah but i cant make mac builds on windows so i will only need one command and it doesn't really matter if i hav a justfile or one batchfile

**Comment by im-coder-lg** [comment]
Who said you need a Mac to make Mac builds? Try AppImages, they can be an all-in-one package with an install script. Trust me, it works.

**Comment by im-coder-lg** [comment]
I found this on Reddit. It is two years old, but I bet it works.

https://www.reddit.com/r/Python/comments/gia4b1/making_python_appimages_using_a_single_command/

**Comment by im-coder-lg** [comment]
PS: AppImages work on macOS too.

**Comment by sumeshir26** [comment]
@im-coder-lg We can use linuxdeploy for the AppData folder

**Comment by sumeshir26** [comment]
I mean AppDir folder

**Comment by im-coder-lg** [comment]
There is nothing on Linux called AppDir. If you are talking libraries, the correct path is `/usr/lib`.

**Comment by im-coder-lg** [comment]
And anyone know about how to successfully run PyInstaller on Linux without missing dependency issues?

**Comment by sumeshir26** [comment]
No, to build a AppImage you need a AppDir directory in the project root. Check the python-appimage docs
What missibg deps error are you getting?

**Comment by im-coder-lg** [comment]
Yeah, Tkinter gone. Even though I installed it from the Pop!_ OS APT repos, which means the file can't find the module. I have an idea, I'll try tomorrow. Get some sleep guys.

**Comment by sumeshir26** [comment]
Try installing from sudo apt-get install python3-tk

**Comment by im-coder-lg** [comment]
I just did this: `sudo nala install python3-tk python-tk tk-dev -y` to get all Tkinter files, and I think I know a fix. I'll do it tomorrow, and it's literally 10:21 PM IST, get some sleep.

**Comment by im-coder-lg** [comment]
I think I got it. Try this command after installing all requirements:

```shell
user@host~$ pyinstaller ./main.py --onefile --windowed --collect-data sv_ttk --collect-all tkinter --collect-all playsound --collect-all darkdetect --icon "./assets/logo.ico"
```

Then move the executable to the directory where the assets are present, then run the executable.

**Comment by im-coder-lg** [comment]
@not-nef try the same on your Mac Mini too.

**Comment by sumeshir26** [comment]
And we can use the inno setup CI to build a installer using github avtions

**Comment by im-coder-lg** [comment]
Oh goody

btw what is this:

https://github.com/Futura-Py/TimerX/blob/b33bced3de0ba13ffe0e14a943f6c4db11a0f374/main.py#L39

no title?

**Comment by im-coder-lg** [comment]
I need to change some paths of the main.py file for Linux, since we need to add it to the OS, we have to make a .desktop file, and make sure assets are accessible through a share folder. I have an idea, and I know it will work.

**Comment by im-coder-lg** [comment]
Then, I have to make a script that runs with sudo to move it to the /usr directories and copy the .desktop file to the app list and desktop.

**Comment by HuyHung1408** [comment]
> Oh goody
> 
> btw what is this:
> 
> https://github.com/Futura-Py/TimerX/blob/b33bced3de0ba13ffe0e14a943f6c4db11a0f374/main.py#L39
> 
> no title?

yep no window name

**Comment by im-coder-lg** [comment]
I have to fix this too... My holidays will be over tomorrow... Why is a teenage life so cursed like this?

**Comment by im-coder-lg** [comment]
I think we should stick with PyInstaller from now on. @not-nef can you build TimerX with the given command(above) and test it?

**Comment by not-nef** [comment]
Remind me tomorrow

**Comment by not-nef** [comment]
yo @HuyHung1408 can i get collab access for mica run i have some ideas for it

**Comment by HuyHung1408** [comment]
> yo @HuyHung1408 can i get collab access for mica run i have some ideas for it

I added it for ya

**Comment by not-nef** [comment]
Thanks

**Pull request merged**
