### PR TITLE
fix: Actions

### PR DESCRIPTION
**Pull request by sumeshir26**

### CODE REVIEW

**Comment by sumeshir26** [comment]
@im-coder-lg Could you look  over the actions tab in your fork? I ran the new actions, and they fail

**Comment by im-coder-lg** [comment]
It's fairly simple. You didn't supply the tag name, I will fix this.

**Comment by im-coder-lg** [comment]
But... You supplied it...

**Comment by im-coder-lg** [comment]
Hold up, kinda fixed Windows, rerunning in 1 minute.

**Comment by im-coder-lg** [comment]
We did it. Literally meant by 9328523's commit message. Problem solved.
The thing was, I did rename the Workflow Dispatch triggers, but forgot to change the YAML corresponding values, the ones that begin with `${{`, so that's one thing. The second one is, I really forgot that a replica of the file with Workflow Dispatch should exist since the main branch is `master`, not `actions-fix`. So thanks for fixing that. The PR is ready for merge, I will create a discussion now with some tasks for each of us, like testing, etc.
Also, can we upload a Windows unpacked version as a ZIP file? Since the MSI installer gave me a nuh-uh, can we upload an unpacked version for Windows?

**Comment by sumeshir26** [comment]
@im-coder-lg the owner of cx_freeze might help us withthat. Would you mind putting the screenshot of the issue and our setup.py over on the cx_freeze issue?

**Comment by sumeshir26** [comment]
Also, since kit is your fork, i dont get access to the draft releases so can you make a test release for me to check?

**Comment by im-coder-lg** [comment]
I hope it's clear, took it on my phone since I turned my PC off to prevent the overheat it had.

**Comment by sumeshir26** [comment]
@im-coder-lg Great! Can you give me the checklist to do?

**Comment by im-coder-lg** [comment]
Creating the discussion!

**Comment by im-coder-lg** [comment]
https://github.com/sumeshir26/TimerX/discussions/10
Linked here, I'll document changes, need to change that too!

**Comment by im-coder-lg** [comment]
@sumeshir26 did you delete any comments of mine recently?

**Comment by sumeshir26** [comment]
@im-coder-lg I was just cleaning up the comments.
Is this ready for merge?

**Comment by im-coder-lg** [comment]
Yeah, ready for merge.

**Comment by sumeshir26** [comment]
@im-coder-lg Thabk you so much👍🏽!

**Comment by im-coder-lg** [comment]
No need to mention it. This happens so rarely, your project was intriguing, so I just helped out on this! This is a great project.
Can you just test the actions with the workflow dispatch trigger?

**Comment by sumeshir26** [comment]
@im-coder-lg Wait, will test later today

**Comment by im-coder-lg** [comment]
We got some glitch, so I will fix that.

**Pull request merged**
