### PR TITLE
feat: Dynamic Resizing

### PR DESCRIPTION
**Pull request by not-nef**
https://user-images.githubusercontent.com/83908932/148544832-132482e6-2862-4b21-8b90-2d1a5522856b.mp4

### CODE REVIEW

**Review by im-coder-lg — COMMENTED** [review]
Is this totally ready for merge?

**Comment by sumeshir26** [comment]
@not-nef @im-coder-lg Wait, there are some things I want to add

**Comment by im-coder-lg** [comment]
Phew! I didn't approve easily, since if it's done in one go, there _has_ to be something else to add, right?

**Comment by im-coder-lg** [comment]
Also, from now, the best way of committing is from the CLI, use this method:
```console
$ pip install -r requirements-dev.txt # get pre-commit hooks and commitizen
$ pre-commit install
$ git add . # adds everything
$ cz commit
add anything, type of commit, scope(optional), title, description, if it's a breaking change or not, why, etc.
$ git push
```
Best method.

**Comment by not-nef** [comment]
> @not-nef @im-coder-lg Wait, there are some things I want to add

ok, just tell me what it is and i add it

**Comment by im-coder-lg** [comment]
@sumeshir26 will tell that, also why is Netlify failing?

**Comment by im-coder-lg** [comment]
I knew it! We need to change the base folder to `docs`.

**Comment by not-nef** [comment]
Well can someone pls tell me what to add fgs

**Comment by sumeshir26** [comment]
Is it possible to just change the **width** of the buttons using .configure(width=)?

**Comment by not-nef** [comment]
Well, you can do that, but afaik the width parameter adjusts the width and not the general size of the Button.

**Comment by not-nef** [comment]
So it makes the button wider

**Comment by sumeshir26** [comment]
I know, but still that’s better than nothing

**Comment by not-nef** [comment]
okay, will do that later this day

**Comment by not-nef** [comment]
https://user-images.githubusercontent.com/83908932/148685109-d7ecc58a-a0b7-48e2-96f4-14d5cba99b73.mp4

**Comment by not-nef** [comment]
@sumeshir26 @im-coder-lg pls review

**Comment by im-coder-lg** [comment]
Excellent! Anything else to add?

**Comment by not-nef** [comment]
Nope, all done

**Review by im-coder-lg — APPROVED** [review]
LGTM :tada:

**Comment by not-nef** [comment]
WOOO 🎉🎉🎉

**Comment by im-coder-lg** [comment]
Wait, can you run `isort`? Just to sort the imports, stack them properly. If not, leave it, it might happen accidentally soon.

**Comment by im-coder-lg** [comment]
Great!

**Comment by not-nef** [comment]
@im-coder-lg done (actually thats quite a cool tool tbh)

**Comment by not-nef** [comment]
> Great!

wtf how fast was that

**Comment by im-coder-lg** [comment]
> @im-coder-lg done (actually thats quite a cool tool tbh)

When you enable precommit hooks, it will run every time you commit; you can also try `isort *.py` to sort all PYs.

**Comment by im-coder-lg** [comment]
> wtf how fast was that

Don't blame me, Vivaldi Mail was fast.

**Comment by not-nef** [comment]
whats vivaldi mail

**Comment by im-coder-lg** [comment]
My mail client on my browser.

**Comment by not-nef** [comment]
@sumeshir26 merge?

**Comment by not-nef** [comment]
btw school start again tomorrow (for me) so i will have less time to work on TimerX. 

:(

**Comment by im-coder-lg** [comment]
I know, same for me. I'm a teenager too lol. But I can manage school, it's 
not _too_ hard. Maybe I'll be committing some files during my soon-to-come 
holidays. But don't worry - I'll try fixing some things and try some crazy 
Tk things that might end up as a new feature. Maybe I'll start with editing 
the About page since the TimerX text is too large.

**Comment by not-nef** [comment]
and @sumeshir26 this time, pls use this commit message.

```
feat: Dynamic resizing (#40)
```

So it doesnt list all commits

**Comment by im-coder-lg** [comment]
I'll just rename the PR? That'd be easier, right?

**Comment by im-coder-lg** [comment]
> So it doesnt list all commits

Actually, it's the merge description.

**Comment by not-nef** [comment]
> I'll just rename the PR? That'd be easier, right?

nah, i just dont want that all commits are listed in the master branch commit

**Comment by im-coder-lg** [comment]
> Nah, i just don't want that all commits are listed in the master branch commit

See, we _squash_ and merge, meaning everything is made into one commit. The merge description would have the commit list.

**Comment by not-nef** [comment]
> I know, same for me. I'm a teenager too lol. But I can manage school, it's not _too_ hard. Maybe I'll be committing some files during my soon-to-come holidays. But don't worry - I'll try fixing some things and try some crazy Tk things that might end up as a new feature. Maybe I'll start with editing the About page since the TimerX text is too large. Also, I never provided the gist of the app text, so maybe now's the chance for me to make sure I learn something new.

Well it doesnt go good for me. Since 8th class ive been a complete E Student and it doesnt seem to get better. Before i was pretty average. I have a chemistry exam on wednesday and if my grades dont get better i wont make the year. :(

**Comment by im-coder-lg** [comment]
Well, all the best, hope you do well!

**Comment by im-coder-lg** [comment]
Well, let's try this. Till you return back on Thursday, well just update the documentation and/or add very minor features related to build. I will just edit the about page, minor change. After you are back, we'll resume. I think this is needed since _you_ are the person with the most Python-related commits. I think this is the best way for us to say thank you. Make sure you are well-prepared for that exam and just finish that up! All the best too :)

**Comment by not-nef** [comment]
Thank you so much ❤️

**Comment by im-coder-lg** [comment]
I think we will start with merging this PR and then start updating documentation from #42 till Thursday.

**Comment by sumeshir26** [comment]
> Well it doesnt go good for me. Since the start of 8th class ive been a complete E Student and it doesnt seem to get better. Before, i was pretty average. I have a chemistry exam on wednesday and if my grades dont get better i wont make the year. :(

Good Luck, hope it goes good for you!

**Comment by im-coder-lg** [comment]
Build fails :\ btw saw this come as mail, I'm still busy

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
ait what? the build _fails_!

**Comment by sumeshir26** [comment]
@im-coder-lg No, that was because of an updated workflow file on `master`

**Comment by im-coder-lg** [comment]
Build failed in PR checks, can you please verify?

**Comment by im-coder-lg** [comment]
Oh, okay. I must've done the same on the PR too.

**Pull request merged**
