### PR TITLE
Use Sun Valley Entry Box

### PR DESCRIPTION
**Pull request by not-nef**

### CODE REVIEW

**Comment by not-nef** [comment]
I only tested this on windows so you should probably test it on windows before considering to merge it.

**Comment by not-nef** [comment]
i only tested this on macos so you should maybe see how it looks on windows

**Comment by im-coder-lg** [comment]
Can you send a screenshot of the preview? I mean, clone your fork of TimerX, install all requirements, start the app and take a screenshot, so that we could know what to expect and what not to expect.

**Comment by not-nef** [comment]
Sure!

image

**Comment by not-nef** [comment]
i deleted my fork to open another pr is that bad?

**Comment by sumeshir26** [comment]
@not-nef Hi! Thank you so much for opening this PR, I wanted to do this since forever, but other things  came in the way. In the future, instead of deleting forks, try making branches so you can make multiple PRs properly. Ialso did this mistake the first tome I opened a PR. Thabk you, I will merge when I get on my Pc today or tommorow

**Comment by im-coder-lg** [comment]
That's good, well do a final test and then @sumeshir26 can merge.

**Comment by not-nef** [comment]
> @not-nef Hi! Thank you so much for opening this PR, I wanted to do this since forever, but other things  came in the way. In the future, instead of deleting forks, try making branches so you can make multiple PRs properly. Ialso did this mistake the first tome I opened a PR. Thabk you, I will merge when I get on my Pc today or tommorow

I tried making a branch for the banner pr, but it also contained the commits for this pr

**Comment by im-coder-lg** [comment]
Hmm... Can you grant me collaborator access to your fork? Maybe I could help.

**Comment by im-coder-lg** [comment]
I know what the problem is as well as the solution. First, I'll test, then I'll go ahead with my plan.

**Comment by not-nef** [comment]
> Hmm... Can you grant me collaborator access to your fork? Maybe I could help.

That fork no longer exists lmao

**Comment by not-nef** [comment]
i only have the fork for the banner pr

**Comment by im-coder-lg** [comment]
Grant me collaborator access to that, I'll manage the rest :wink:

**Comment by not-nef** [comment]
oke, gimme a sec

**Comment by not-nef** [comment]
done

**Comment by not-nef** [comment]
@im-coder-lg

**Comment by im-coder-lg** [comment]
I have a good idea, working on that now.

**Comment by not-nef** [comment]
cool

**Comment by im-coder-lg** [comment]
@not-nef close this PR, we'll manage this in #18

**Pull request closed without merging**
