### PR TITLE
feat(docs): Build test workflow

### PR DESCRIPTION
**Pull request by im-coder-lg**
We need that.

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Also, since the settings page is added now, can we cross that in the README?

**Comment by im-coder-lg** [comment]
Moreover, TimerX has become very stable, so maybe v1.0 can be released between end of Jan/beginning of Feb?

**Comment by sumeshir26** [comment]
> Moreover, TimerX has become very stable, so maybe v1.0 can be released between end of Jan/beginning of Feb?

Thats the plan

**Comment by sumeshir26** [comment]
> Also, since the settings page is added now, can we cross that in the README?

Doing that now

**Review by sumeshir26 — APPROVED** [review]

**Pull request merged**
