### PR TITLE
About window

### PR DESCRIPTION
**Pull request by not-nef**
Its done. And also: @sumeshir26 i fixed your „improvements“. You should test your changes in the future.

### CODE REVIEW

**Comment by not-nef** [comment]
I request merging.

**Comment by im-coder-lg** [comment]
Testing this bro!

**Review by im-coder-lg — APPROVED** [review]
LGTM! Don't merge this immediately though.

**Review by im-coder-lg — COMMENTED** [review]
LGTM! Don't merge this immediately though.

**Comment by not-nef** [comment]
> LGTM! Don't merge this immediately though.

ofc, still need sumeshirs review, but cool that you like it

**Comment by im-coder-lg** [comment]
Wait why's there no checks?

**Comment by not-nef** [comment]
there were checks

**Comment by not-nef** [comment]
image

**Comment by not-nef** [comment]
or did you mean any other checks?

**Comment by not-nef** [comment]
Ah, you meant the build checks right? no idea why it didnt do any. but i think it should work since the script runs with no problems.

**Comment by im-coder-lg** [comment]
> Ah, you meant the build checks right?

Yeah. No wonde why it didn't load here... Oh no you reminded me, I need to make a Docusaurus check lmao forgot that! Making that tomorrow!

**Comment by sumeshir26** [comment]
@not-nef Can I get collaborator access for your new fork?

**Comment by im-coder-lg** [comment]
This works, I can guarantee that.

**Comment by im-coder-lg** [comment]
Although, TimerX is getting much slower with more code. I have observed this, maybe that's why I objected to merging configurator code.

**Comment by sumeshir26** [comment]
@im-coder-lg Where is it getting slower?
What are your pc's Specs?

**Comment by im-coder-lg** [comment]
> Where is it getting slower?

Whenever I launch it.
> What are your PC's Specs?

Intel Core i3, 4 GB RAM, an HDD of Windows and an SSD of my folders. Ultra-fast legendary speed for me.

**Comment by not-nef** [comment]
Well no offense but thats pretty bad. And if you have an Ssd, why dont you use it for windows?

**Comment by not-nef** [comment]
> @not-nef Can I get collaborator access for your new fork?

what, why?

**Comment by im-coder-lg** [comment]
> Well no offense but thats pretty bad. And if you have an Ssd, why dont you use it for windows?

None taken. I have another computer but since I filled it up with my phone backups, I'll have to backup the important parts and reinstall Windows. It's 8 GB, but I like my 4 GB one. And speaking of the SSD, I didn't install it, it came preinstalled so idk which is Windows lol.

**Comment by im-coder-lg** [comment]
Oh, forgot, it's Core i5, noticed it while running my Windows XP VM.

**Comment by not-nef** [comment]
cool, i also have an i5

**Comment by sumeshir26** [comment]
Mee to(10th Gen Core i5, 8GB Ram)

**Comment by sumeshir26** [comment]
i need you to give me collaborator access so I can checkout and commit using the Github CLI

**Comment by im-coder-lg** [comment]
> Mee to(10th Gen Core i5, 8GB Ram)

**Comment by not-nef** [comment]
> i need you to give me collaborator access so I can checkout and commit using the Github CLI

ooke

**Comment by not-nef** [comment]
done

**Comment by im-coder-lg** [comment]
Totally complete?

**Comment by not-nef** [comment]
yup

**Comment by not-nef** [comment]
@sumeshir26 review pls

**Comment by not-nef** [comment]
> Although, TimerX is getting much slower with more code. I have observed this, maybe that's why I objected to merging configurator code.

Try compiling it (runs faster)

**Comment by not-nef** [comment]
atleast for me

**Review by sumeshir26 — APPROVED** [review]

**Comment by not-nef** [comment]
🎉

**Pull request merged**
