### PR TITLE
feat: Dark mode

### PR DESCRIPTION
**Pull request by sumeshir26**
@im-coder-lg Can you test on Zorin OS

### CODE REVIEW

**Comment by im-coder-lg** [comment]
I haven't switched yet. Yeah I need permission to switch and it's best done on a Sunday, but I could try Raspbian.

**Comment by im-coder-lg** [comment]
Well I'll do it soon, maybe by tonight since I got some work to do.

**Comment by im-coder-lg** [comment]
It fails at the icon script... Maybe instead of `linux` we need to use `aarch64` or `armv7l` for Raspberry Pi users, and `amd64`, `arm64` for 64-bit systems.

**Comment by im-coder-lg** [comment]
It's the JPEG that disturbs btw

**Comment by im-coder-lg** [comment]
You don't need to remove the already-existing builds. I saw that Ubuntu succeded, but WIndows, it doesn't know what `rm` is. I will experiment on this and make sure the checks succeed.

**Comment by sumeshir26** [comment]
> Have you added a toggle for dark mode here?

No, it should detect the system theme via darkdetect

**Comment by im-coder-lg** [comment]
Couldn't experiment checks but I am going to switch to Zorin soon so you have a Linux+Windows(Windows App Support) tester here, but the checks issue, maybe I will edit and send a PR to `dark-mode`.

**Comment by sumeshir26** [comment]
@im-coder-lg I asked you to test on zor in because I know tha zorin had a dark mode and I wanted to test dark mode detection on zorin

**Comment by im-coder-lg** [comment]
Did it work on Windows? As of now, I think it will fail due to the 
icon(JPEG didn't seem to work on Raspbian) but let's see, it would take a 
lot of time to switch to Zorin.

**Comment by sumeshir26** [comment]
It does work on Windows 11 but dark mode on Linux is kind weird because of the many distros

**Comment by sumeshir26** [comment]
@im-coder-lg Try now

**Comment by im-coder-lg** [comment]
Dude I don't have Zorin installed yet! It might work so just comment out the Linux platform code, it seems to disturb the run.

**Comment by im-coder-lg** [comment]
I think I could do the test tomorrow/Sunday. Flashing time, going into the boot meny, and till it's successfully installed, it will take a lot of time. But what about Gitpod+Xrdp+Xfce desktop? Till I get Zorin?

**Comment by sumeshir26** [comment]
@im-coder-lg I’ll try… I will try on replit first

**Comment by im-coder-lg** [comment]
Wow. I'll be gone for long, I think I'll be _finally_ getting Zorin. Before the installation(which is due evening), however, I'll check on my Win7 PC.

**Review by im-coder-lg — CHANGES_REQUESTED** [review]
https://github.com/sumeshir26/TimerX/blob/224d91c416e24e83d5b86d1ccf3d9cb48b3b442a/main.py#L24
I think you have to change `Windows` to `win32` since it fails if it's Windows for me. Does it fail the same for you?

**Comment by sumeshir26** [comment]
@im-coder-lg Nope?

**Comment by im-coder-lg** [comment]
Woah, massive bug? Windows 10 also has 32-bit apps, so why not make the change? I have used Windows 10 for a few years, and I got this new PC(well not new, kinda 10 years old) but the dark mode does work. Although it moves the layout a bit, it works fine.
We must find out if Windows 11 supports 33-bit apps or we could just change it to `win`. What do you think?

**Comment by sumeshir26** [comment]
@im-coder-lg Windows 11 _does_ support 32 bit apps but does not support 32 bit _PCs_

**Comment by sumeshir26** [comment]
@im-coder-lg Try now

**Comment by im-coder-lg** [comment]
Well, voila. We can use win32 as the code. Windows 11 uses win32 apps but not win32 systems... We can use win32.

**Comment by im-coder-lg** [comment]
And don't use caps for the system code. `Darwin` might render as invalid but `darwin` won't.

**Comment by im-coder-lg** [comment]
2 minutes please.

**Comment by im-coder-lg** [comment]
Windows failed. Console logs:
```console
$ python main.py
  File "main.py", line 19
    elif  platform.system() == "darwin":
    ^
SyntaxError: invalid syntax
```
PS: Using Git Bash since I am a Bash enthusiast.

**Comment by sumeshir26** [comment]
@im-coder-lg Alreaday fixed. Try again

**Comment by im-coder-lg** [comment]
Seems to work _and_ use the JPEG at the same time... Anyway, I'm switching soon, so this ain't much of a problem.

**Comment by im-coder-lg** [comment]
Great!

**Pull request merged**
