### PR TITLE
fix: gp and feat: Commitizen and pre-commit hooks

### PR DESCRIPTION
**Pull request by im-coder-lg**
An enhancement to commit writing and fixing Gitpod. I'd like to make a new label for Gitpod for PRs that add extra Gitpod functionality.

~~NOT READY YET~~ Ready!

### CODE REVIEW

**Comment by im-coder-lg** [comment]
I'll mark this ready when ready. A new label for that too?

**Comment by sumeshir26** [comment]
Yeah

**Comment by im-coder-lg** [comment]
Created that with a green colour. I am testing pre-commit hooks, those are _the most important part. It has a formatter named `black` that formats code. I found it [here](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/).
Also, just realized, this was written by a person I know on GitHub.

**Comment by im-coder-lg** [comment]
Gitpod is slowing down.

**Comment by im-coder-lg** [comment]
Damn, for 21f4dbf, I almost rage-quitted! Commitizen expected perfection dude! It WORKS!!!
Next, Gitpod.

**Comment by im-coder-lg** [comment]
It's better for people to use the CLI method to commit.

**Comment by im-coder-lg** [comment]
That is Commitizen. Works, right?

**Comment by sumeshir26** [comment]
Gitpod says that it fails

**Comment by im-coder-lg** [comment]
Yeah I have encountered this. The image isn't updated properly though. I think I might be getting onto an idea of sorts, like maybe I'll try doing what the Gitpod people tell us, install Tk-dev from the APT repos. I will try that and report back. Need some free time.

**Comment by im-coder-lg** [comment]
Done a bunch of fixes.

**Comment by im-coder-lg** [comment]
I'm confused about the Gitpod part, I will fix that soon. For now, everything works perfectly. Maybe soon, I will try using shell scripts for automation. What's your opinion?

**Comment by im-coder-lg** [comment]
We are getting some help soon! https://github.com/gitpod-io/workspace-images/issues/609#issuecomment-1006593489

**Comment by im-coder-lg** [comment]
I added isort. Don't take me wrong and no offense, we do good work but this was how it looked before isort:
```python
# TimerX v0.2 by sumeshir26
# IMPORTS
ver = "0.9"

from time import sleep
from tkinter import  TclError, ttk, Tk, PhotoImage, Frame, StringVar
import tkinter
from tkinter.constants import  LEFT
from playsound import playsound
from threading import  Thread
from platform import system
import os
from utils import *
import webbrowser
"""
# Disabled by default due to module unavailability on Linux
from BlurWindow.blurWindow import GlobalBlur, blur
"""
import darkdetect

from tkinter.messagebox import showinfo
```
This was how it looked after:
```python
# TimerX v0.2 by sumeshir26
# IMPORTS
ver = "0.9"

import os
import tkinter
import webbrowser
from platform import system
from threading import Thread
from time import sleep
from tkinter import Frame, PhotoImage, StringVar, TclError, Tk, ttk
from tkinter.constants import LEFT

from playsound import playsound

from utils import *

"""
# Disabled by default due to module unavailability on Linux
from BlurWindow.blurWindow import GlobalBlur, blur
"""
from tkinter.messagebox import showinfo

import darkdetect
```
That seems neat right? Also, I need to stop speed typing since I messed up the commit message lol.

**Comment by im-coder-lg** [comment]
I like that way it clarified single imports first then the submodules were added. Neatness 100x%. @not-nef from now, we'll follow the Commitizen way of making commits. It's better in a good way.

**Comment by not-nef** [comment]
what

**Comment by im-coder-lg** [comment]
> what

Shocked? I don't understand. This is an easier way of handling Git and version control. Instead of `Adding an image to the blog`, you could try `feat(blog): add image`, which is simpler, right?

**Comment by im-coder-lg** [comment]
I'll try this for Gitpod:
https://github.com/gitpod-io/workspace-images/issues/609#issuecomment-1006673856

**Comment by im-coder-lg** [comment]
We are ready for merging! Thanks a lot @axonasif for hosting our image on Docker Hub! If it's costing you, do tell us, we'll try having it on the repo.

**Comment by im-coder-lg** [comment]
I'll just clean up and we'll be good to go.

**Comment by axonasif** [comment]
> We are ready for merging! Thanks a lot @axonasif for hosting our image on Docker Hub!

You're welcome, glad to know it works!

> If it's costing you, do tell us, we'll try having it on the repo.

I'm new to using dockerhub, does it really cost the user for pulls by other people?

**Review by sumeshir26 — APPROVED** [review]
LGTM🎉

**Comment by im-coder-lg** [comment]
Also @sumeshir26 please remember to remove private things like your PC path and etc. I have removed one of it from the `pyvenv.cfg` file and added Windows PATHs.

**Comment by im-coder-lg** [comment]
> I'm new to using docker hub, does it really cost the docker hub repo-owner for pulls by other people?

idk, but when I was about to host my version of the same Dockerfile, it asked me to pay. Maybe it's for server maintenance.
But, thanks _a lot_ for helping with this!

**Comment by im-coder-lg** [comment]
@not-nef need your opinion too! What do you think of Commitizen conventional commit schema? They even have other ones, so if you like another one better than this, I can change it later.

**Comment by im-coder-lg** [comment]
Merge? @not-nef your ideas!

**Comment by sumeshir26** [comment]
> Merge?

Waiting on @not-nef's review before merging

**Review by not-nef — APPROVED** [review]

**Comment by im-coder-lg** [comment]
I'll merge?

**Comment by not-nef** [comment]
ig

**Pull request merged**
