### PR TITLE
patch(readme): readme spelling errors and more

### PR DESCRIPTION
**Pull request by im-coder-lg**
So, I corrected basic spelling errors, which might have happened during a speed type, added some spaces in the Supported Platforms' emojis so that it'd look neat, arranged all emojis and replaced `Keybinds` with `Keybindings` in `Keybindings to Play/Pause`, that seems more correct. Also removed the Zorin part in Linux(Supported platforms) since I haven't installed it yet(lazy me). More info in the release tasks discussion.
Also, can we use the new icon as an emoji? I have a plan just for that.

### CODE REVIEW

**Comment by im-coder-lg** [comment]
We need to change more things too. Also, forgot to tell, I didn't remove Zorin from the Readme, I commented it out(`<!--comment-->`)

**Comment by sumeshir26** [comment]
What more things do we neex to change? And, emoji as icon? I have never heard of that!

**Comment by im-coder-lg** [comment]
It's kind of a HTML cheat, here, look at this:
```html
<div align=center>
<img alt="TimerX icon" width="48px" src="https://raw.githubusercontent.com/sumeshir26/TimerX/master/assets/logo_new.png">
</div>
```
Output:

<div align=center>
TimerX icon
</div>

---

You can adjust the pixel size with the `width` tag.

We could try that

**Comment by im-coder-lg** [comment]
> What more things do we neex to change?

Need to check, brb.

**Comment by sumeshir26** [comment]
Dont update anything! the actions error is caused by you using tje version 1.0-test In setup.py it explicitly specifies the version aas 1.0 so you need to specify the version while running tje action as 1.0

**Comment by im-coder-lg** [comment]
okay, testing again.

**Comment by im-coder-lg** [comment]
Well, now it works. Are we heading straight to v1.0 or alpha build, then beta and finally, 1.0?

**Comment by im-coder-lg** [comment]
Wait wdym? We are making an alpha release first?

**Comment by im-coder-lg** [comment]
Also is the icon-to-emoji okay? Maybe I can put it on the README.

**Comment by im-coder-lg** [comment]
Also, `pyvenv.cfg` has a private Windows PATH... How about asking users to make a special path for the Python VENV?

**Comment by im-coder-lg** [comment]
Also, I was wondering about adding a nice contributing guide here, what do you say? Adding that and maybe even a wiki/website, you can deploy it, I can take care of it. Need your opinions on this.

**Comment by im-coder-lg** [comment]
/ping @sumeshir26 can you review, tell if I can change the header to the one with our new icon and/or tell a go-ahead for merge?

**Comment by sumeshir26** [comment]
@im-coder-lg No need to add tkinter to requirements.txt since it is a built in module in python but others like play sound and darkdetect are not

**Comment by sumeshir26** [comment]
Yeah, you can change the header. (Also, to me it somehow seems that we are confusing not-nef more than helping on his Branch/Fork Question 😂

**Comment by im-coder-lg** [comment]
> @im-coder-lg No need to add tkinter to requirements.txt since it is a built in module in python but others like play sound and darkdetect are not

Ok... But in Replit, on first run, it asks me what the heck is Tkinter? Well, maybe let it be there so that users that use the cloud like Replit or Gitpod can install Tk easily.

**Comment by im-coder-lg** [comment]
> Yeah, you can change the header.

Will do...
> Also, to me it somehow seems that we are confusing not-nef more than helping on his Branch/Fork Question 😂

Well, maybe for this I will have to elaborate.

**Comment by im-coder-lg** [comment]
Testing release build so that this doesn't fail during the release creation.

**Review by sumeshir26 — APPROVED** [review]
LGTM

**Comment by im-coder-lg** [comment]
> Okay, How do you suggest to make a website?

Documentation? We'll make a `docs/` directory here. I will use a workflow that deploys my favourite CODEDOC to GitHub Pages, and we are good to go.

**Comment by im-coder-lg** [comment]
We could also use Jekyll that can use Vercel... Let's take Jekyll, that's widely supported and we will use Netlify for the website deployment since it has Netlify CMS that could allow us to edit without going to GitHub.

**Comment by sumeshir26** [comment]
Hmm.. Action fails badly

**Comment by im-coder-lg** [comment]
We need to use only integers, no `alpha` tags. Maybe we could name the release as alpha and use `1.0.01` or something else.

**Comment by sumeshir26** [comment]
Ok, name could be 0.9

**Comment by im-coder-lg** [comment]
Changing now!

**Comment by im-coder-lg** [comment]
LGTM, people! Let's get ready to merge after a final test.

**Comment by im-coder-lg** [comment]
Merging!
image

**Pull request merged**
