### PR TITLE
About Window

### PR DESCRIPTION
**Pull request by not-nef**
Screenshot 2022-01-01 160908

### CODE REVIEW

**Comment by not-nef** [comment]
@sumeshir26 what links do you want for the about page?

and

@im-coder-lg whats the domain of the website? (or is it even online?)

**Comment by im-coder-lg** [comment]
> whats the domain of the website? (or is it even online?)

@sumeshir26 said he'll activate Vercel on Wednesday but it better be `timerx.vercel.app`, that's easily recognised by us.

**Comment by im-coder-lg** [comment]
> what links do you want for the about page?

My opinion, GitHub link, website and maybe Sun Valley's link. Also in the about page can we add some minimal Readme? I will share the text here soon.

**Comment by im-coder-lg** [comment]
Also the text font, can you try Google Sans or Source Code Pro? Check Google Fonts for Montserrat too!

**Comment by not-nef** [comment]
> > what links do you want for the about page?
> 
> My opinion, GitHub link, website and maybe Sun Valley's link. Also in the about page can we add some minimal Readme? I will share the text here soon.

ok, but it better not be too long or else the window gets huge

**Comment by not-nef** [comment]
> Also the text font, can you try Google Sans or Source Code Pro? Check Google Fonts for Montserrat too!

okay

**Comment by not-nef** [comment]
Source code pro looks a bit retro eh? im kind of happy with the current font for the title (Its `Arial Round MT Bold`, it comes with windows). But for the Version, the buttons and the readme, i would like to you Source Sans Pro:

image

Yes/No?

@im-coder-lg

**Comment by im-coder-lg** [comment]
Yeah that is what I need. Optionally, I'd use Montserrat too, it's simplistic, kinda.

**Comment by not-nef** [comment]
oh mah god im a collabsorator !!1!1!!!!

**Comment by sumeshir26** [comment]
@not-nef Use Segoe UI Variable for the font. It comes with windows 11

**Comment by not-nef** [comment]
alright, but can we keep `Arial Round MT Bold` for the title (the `TimerX` text)?

**Comment by sumeshir26** [comment]
Okay 👍

**Comment by not-nef** [comment]
@im-coder-lg i accidentally commited to the master branch of my fork. how do i get rid of it?

**Review by im-coder-lg — COMMENTED** [review]
Anything more @not-nef? Also, a sidenote: Ask people before merging a PR. Let atleast one approval in the PR to know it's ready for merge. Just a note you'll have to be careful now that you're a collaborator (congrats bro btw how'd you get access too?)

**Comment by im-coder-lg** [comment]
> @im-coder-lg I accidentally committed to the master branch of my fork. how do I get rid of it?

Revert commit or undo changes? Maybe undo changes, then after merging make another fork(what a headache)

**Pull request closed without merging**
